/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pilhaswing;



/**
 *
 * @author Edgard Lamounier
 */
public class jfPilhaSwing extends javax.swing.JFrame {

    /**
     * Creates new form jfPilhaSwing
     */
    public jfPilhaSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbPush = new javax.swing.JButton();
        jbPop = new javax.swing.JButton();
        jbPrint = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaVePilha = new javax.swing.JTextArea();
        jlNro = new javax.swing.JLabel();
        jtfNumero = new javax.swing.JTextField();
        jbMaior = new javax.swing.JButton();
        jbMenor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simula Pilha");

        jbPush.setText("PUSH");
        jbPush.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbPushMouseClicked(evt);
            }
        });

        jbPop.setText("POP");
        jbPop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbPopMouseClicked(evt);
            }
        });

        jbPrint.setText("PRINT");
        jbPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbPrintMouseClicked(evt);
            }
        });

        jtaVePilha.setColumns(20);
        jtaVePilha.setRows(5);
        jScrollPane1.setViewportView(jtaVePilha);

        jlNro.setText("Número: ");

        jbMaior.setText("MAIOR");

        jbMenor.setText("MENOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlNro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfNumero)
                                .addGap(13, 13, 13))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbPush)
                                .addGap(18, 18, 18)
                                .addComponent(jbPop)
                                .addGap(18, 18, 18)
                                .addComponent(jbPrint)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jbMaior)
                        .addGap(28, 28, 28)
                        .addComponent(jbMenor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNro)
                            .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbPush)
                            .addComponent(jbPop)
                            .addComponent(jbPrint))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbMaior)
                            .addComponent(jbMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbPushMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPushMouseClicked
        int nro;
        nro = Integer.parseInt(jtfNumero.getText());
        pilha.push(nro); 
        // pilha.push( Integer.parseInt(jtfNumero.getText()) );
        System.out.println("Empilhei o " + nro);
                
    }//GEN-LAST:event_jbPushMouseClicked

    private void jbPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPrintMouseClicked
        //pilha.printConsole();
        jtaVePilha.setText(pilha.printAreaTexto());
    }//GEN-LAST:event_jbPrintMouseClicked

    private void jbPopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPopMouseClicked
        int nro;
        
        nro = pilha.pop(); 
    }//GEN-LAST:event_jbPopMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfPilhaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfPilhaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfPilhaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfPilhaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfPilhaSwing().setVisible(true);
            }
        });
    } // fim do void main()
    
    private Pilha  pilha = new Pilha();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbMaior;
    private javax.swing.JButton jbMenor;
    private javax.swing.JButton jbPop;
    private javax.swing.JButton jbPrint;
    private javax.swing.JButton jbPush;
    private javax.swing.JLabel jlNro;
    private javax.swing.JTextArea jtaVePilha;
    private javax.swing.JTextField jtfNumero;
    // End of variables declaration//GEN-END:variables

}
